# Project information
site_name: Progressive Web Apps
site_description: Lehrmaterial, Übungen, Aufgaben und Hilfen für Aktuelle Trends der IKT
site_author: Jörn Freiheit
site_url: http://freiheit.f4.htw-berlin.de/ikt

# Repository
repo_name: webtech
repo_url: https://github.com/jfreiheit/ikt_2023

# Copyright
copyright: Copyright &copy; 2023 Jörn Freiheit

# Configuration
theme:
  name: material
  language: de
  palette:
    primary: grey
    accent: indigo
  features:
    - instant
    - tabs
    - navigation.footer
    - navigation.instant
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.tabs.link
  font:
    text: Roboto
    code: Roboto Mono
  favicon: img/favicon.png
  logo: img/fiw.jpg


extra_css:
  - extra.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - meta 
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

#Navigation
nav:
    - Home: index.md
    - Einführung: einfuehrung.md 
    - Grundgerüst: grundgeruest.md 
    - Manifest: manifest.md
    - Service worker: serviceworker.md 
    - Promises & Fetch-API: promises.md 
    - Caching: caching.md 
    - Backend: backend.md 
    - IndexedDB: indexeddb.md 
    - Bilder speichern: bilder.md 
    - Kamera: kamera.md 
    - Geolocation: geolocation.md 
    - Hintergrundsynchronisation: backgroundsync.md 
    - Push Notifications: pushnotes.md 
    - Übungen: uebungen.md 
    - Tools: tools.md 

